image:
  repository: <AWS_ACCOUNT_ID>.dkr.ecr.ap-south-1.amazonaws.com/flask-backend
  tag: latest
service:
  type: ClusterIP
  port: 5000
env:
  DB_HOST: mysql-service
  DB_USER: root
  DB_PASSWORD: password
  DB_NAME: app_db
